name: Update Service From Release

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment where has to be deployed Qa / Prod'     
        required: true
        default: ''
      git-ref:
        description: Git Ref (Optional)    
        required: true
  release:
    types: [created]

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        ref: ${{ github.event.inputs.git-ref }}
                  
                
    - name: (GLOBAL) Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
    - name: (GLOBAL) Define variables
      id: Variables
      #if: github.event.pull_request.opened == true #github.ref == 'refs/heads/develop' || 
      run: |	  
        echo "ECS_CLUSTER=${{secrets.ECS_CLUSTER}}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{github.event.inputs.git-ref}}" >> $GITHUB_ENV
        echo "ECS_SERVICE=${{secrets.ECS_SERVICE}}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=${{secrets.ECS_SERVICE}}" >> $GITHUB_ENV
        echo "NPM_TOKEN=${{secrets.NPM_TOKEN_PARAM}}" >> $GITHUB_ENV      

# Qa Assume role        
    - name: (QA) Assume role
      uses: aws-actions/configure-aws-credentials@v1
      if: contains(github.event.inputs.Environment, 'Qa')
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.QA_AWS_ACCOUNT }}:role/Devops-Role
        role-duration-seconds: 1200
        role-session-name: GithubActions-Qa

    - name: (QA) Login to Amazon ECR
      id: login-ecr-qa
      if: contains(github.event.inputs.Environment, 'Qa')
      uses: aws-actions/amazon-ecr-login@v1        

    - name: (QA) Deploy to FARGATE ${{secrets.ECS_SERVICE}}
      id: Deploy-image-qa
      if: contains(github.event.inputs.Environment, 'Qa')
      run: |
        echo "===================================="
        echo "DEBUG:"
        echo "ECR_REPOSITORY: ${ECS_SERVICE}"
        echo "IMAGE_TAG: $IMAGE_TAG"
        echo "ECS_SERVICE: ${ECS_SERVICE}"
        echo "ECS_CLUSTER: ${ECS_CLUSTER}"
        echo "===================================="
        echo "Describe Task definition: ${ECS_SERVICE}"
        echo "===================================="
        aws ecs describe-task-definition --task-definition ${ECS_SERVICE} >> "${ECS_SERVICE}.json"
        export NEW_IMAGE_TAG="${{ steps.login-ecr-qa.outputs.registry }}/${ECS_SERVICE}:$IMAGE_TAG"
        cat ${ECS_SERVICE}.json | jq --arg IMAGE "$NEW_IMAGE_TAG" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)' >> APP.json
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x ./jq-linux64
        sudo cp -f jq-linux64 /usr/bin/jq
        aws ssm get-parameters-by-path --path /modfi --query "Parameters[*].{name:Name,valueFrom:ARN}" | /usr/bin/jq -c --arg replace /modfi/ 'walk(if type == "object" and has("name") then .name |= gsub($replace;"") else . end)' > SECRETS
        aws ssm get-parameters-by-path --path /${ECS_SERVICE} --query "Parameters[*].{name:Name,valueFrom:ARN}" | jq -c --arg replace /${ECS_SERVICE}/ 'walk(if type == "object" and has("name") then .name |= gsub($replace;"") else . end)' > SECRETS${ECS_SERVICE}
        cat APP.json | jq 'del(.containerDefinitions[0].secrets)' > json2
        rm -f APP.json              
        jq --argjson groupInfo "$(cat SECRETS)" '.containerDefinitions[0].secrets += $groupInfo' json2 >> APP${ECS_SERVICE}.json
        jq --argjson groupInfo "$(cat SECRETS${ECS_SERVICE})" '.containerDefinitions[0].secrets += $groupInfo' APP${ECS_SERVICE}.json >> APP.json        
        echo "===================================="
        echo "Registering Task definition"
        echo "===================================="
        PORT=$(cat ${ECS_SERVICE}.json | jq .taskDefinition.containerDefinitions[0].portMappings[0].containerPort)
        NEW_TASK_INFO=$(aws ecs register-task-definition --region $AWS_DEFAULT_REGION --family ${ECS_SERVICE} --cli-input-json file://APP.json)
        NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
        echo "===================================="
        echo "Updating service / CodeDeploy run"
        echo "===================================="
        aws deploy create-deployment --application-name ${ECS_SERVICE} --deployment-group-name ${ECS_SERVICE}-dg \
        --revision '{"revisionType": "AppSpecContent", "appSpecContent": {"content": "{\"version\": 1, \"Resources\": [{\"TargetService\": {\"Type\": \"AWS::ECS::Service\", \"Properties\": {\"TaskDefinition\": \"'arn:aws:ecs:${AWS_DEFAULT_REGION}:${{secrets.DEV_AWS_ACCOUNT}}:task-definition/${ECS_SERVICE}:${NEW_REVISION}'\", \"LoadBalancerInfo\": {\"ContainerName\": \"'${ECS_SERVICE}'\", \"ContainerPort\": \"'${PORT}'\"}}}}],\"Hooks\": [{\"AfterAllowTestTraffic\": \"'${ECS_SERVICE}-AfterAllowTestTraffic'\"}]}"}}' \
        --query deploymentId >> ID
        sleep 10
        aws deploy wait deployment-successful --deployment-id $(cat ID | sed 's|"||g')
        #echo "===================================="
        #echo "Describing Task definition"
        #echo "===================================="
        #cat ${ECS_SERVICE}.json

# Prod Assume role        
    - name: (PROD) Assume role
      uses: aws-actions/configure-aws-credentials@v1
      if: contains(github.event.inputs.Environment, 'Prod')
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT }}:role/Devops-Role
        role-duration-seconds: 1200
        role-session-name: GithubActions-Prod

    - name: (PROD) Login to Amazon ECR 
      id: login-ecr-prod
      if: contains(github.event.inputs.Environment, 'Prod')
      uses: aws-actions/amazon-ecr-login@v1      

    - name: (PROD) Deploy to FARGATE ${{secrets.ECS_SERVICE}}
      id: Deploy-image-prod
      if: contains(github.event.inputs.Environment, 'Prod')
      run: |
        echo "===================================="
        echo "DEBUG:"
        echo "ECR_REPOSITORY: ${ECS_SERVICE}"
        echo "IMAGE_TAG: $IMAGE_TAG"
        echo "ECS_SERVICE: ${ECS_SERVICE}"
        echo "ECS_CLUSTER: ${ECS_CLUSTER}"
        echo "===================================="
        echo "Pushing Docker Image"
        echo "===================================="
        #docker push ${{ steps.login-ecr-prod.outputs.registry }}/${ECS_SERVICE}:$IMAGE_TAG		
        echo "===================================="
        echo "Describe Task definition: ${ECS_SERVICE}"
        echo "===================================="
        aws ecs describe-task-definition --task-definition ${ECS_SERVICE} >> "${ECS_SERVICE}.json"
        export NEW_IMAGE_TAG="${{ steps.login-ecr-prod.outputs.registry }}/${ECS_SERVICE}:$IMAGE_TAG"
        cat ${ECS_SERVICE}.json | jq --arg IMAGE "$NEW_IMAGE_TAG" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)' >> APP.json
        wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x ./jq-linux64
        sudo cp -f jq-linux64 /usr/bin/jq
        aws ssm get-parameters-by-path --path /modfi --query "Parameters[*].{name:Name,valueFrom:ARN}" | /usr/bin/jq -c --arg replace /modfi/ 'walk(if type == "object" and has("name") then .name |= gsub($replace;"") else . end)' > SECRETS
        cat APP.json | jq 'del(.containerDefinitions[0].secrets)' > json2
        rm -f APP.json              
        jq --argjson groupInfo "$(cat SECRETS)" '.containerDefinitions[0].secrets += $groupInfo' json2 >> APP.json        
        echo "===================================="
        echo "Registering Task definition"
        echo "===================================="
        PORT=$(cat ${ECS_SERVICE}.json | jq .taskDefinition.containerDefinitions[0].portMappings[0].containerPort)
        NEW_TASK_INFO=$(aws ecs register-task-definition --region $AWS_DEFAULT_REGION --family ${ECS_SERVICE} --cli-input-json file://APP.json)
        NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
        echo "===================================="
        echo "Updating service / CodeDeploy run"
        echo "===================================="
        aws deploy create-deployment --application-name ${ECS_SERVICE} --deployment-group-name ${ECS_SERVICE}-dg \
        --revision '{"revisionType": "AppSpecContent", "appSpecContent": {"content": "{\"version\": 1, \"Resources\": [{\"TargetService\": {\"Type\": \"AWS::ECS::Service\", \"Properties\": {\"TaskDefinition\": \"'arn:aws:ecs:${AWS_DEFAULT_REGION}:${{secrets.DEV_AWS_ACCOUNT}}:task-definition/${ECS_SERVICE}:${NEW_REVISION}'\", \"LoadBalancerInfo\": {\"ContainerName\": \"'${ECS_SERVICE}'\", \"ContainerPort\": \"'${PORT}'\"}}}}],\"Hooks\": [{\"AfterAllowTestTraffic\": \"'${ECS_SERVICE}-AfterAllowTestTraffic'\"}]}"}}' \
        --query deploymentId >> ID
        sleep 10
        aws deploy wait deployment-successful --deployment-id $(cat ID | sed 's|"||g')
        #echo "===================================="
        #echo "Describing Task definition"
        #echo "===================================="
        #cat ${ECS_SERVICE}.json

    #- name: Slack Notification
    #  uses: rtCamp/action-slack-notify@master
    #  env:
    #    SLACK_CHANNEL: modfi_software
    #    SLACK_COLOR: '#3278BD'
    #    SLACK_MESSAGE: '${{github.event.release.body}} Status: OK'
    #    SLACK_TITLE: Information
    #    SLACK_USERNAME: Github-CICD
    #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
